# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint, Test & Build

# Only Igonore main branch, all other branches will have this action running on push and pr
# In order to run this CI/CD action on a specific branch then 'branches:[ master , develop ..(and so on) ], remove the ingnore
on:
  push:
    branches-ignore: "main"
  pull_request:
    branches-ignore: "main"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'        
    # Node Commands from Package JSON Scripts    
    # Install All Dependecies
    - name: Install CI Dependencies 
    - run: npm ci
    
    # Lint Check for Code Clean up 
    - name: Lint Check
    - run: npm run lint:ci
    
    # Test Angular Unit test with Headless Browser
    - name : Unit Test
    - run: npm run test:ci
    
    # Build Angular Project with prod enviorment
    - name: Build Angular Project
    - run: npm run build:ci
    
    
